### ISSUE TITLE
errors when gulp release

### ISSUE THREAD

**Issue by zackexplosion** [whoisandie/yoda#2]
I got this error when running `gulp release`

```
[15:52:44] Error: ENOENT, no such file or directory './identity'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Gulp.<anonymous> (/Users/zack/projects/yoda/gulpfile.js:171:29)
    at module.exports (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:79:16)
    at Gulp.onTaskEnd (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:68:5)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/zack/projects/yoda/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
[15:52:44] 'release' errored after 9.08 s
[15:52:44] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:79:16)
    at Gulp.onTaskEnd (/Users/zack/projects/yoda/node_modules/run-sequence/index.js:68:5)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/zack/projects/yoda/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/zack/projects/yoda/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)

```

**Comment by whoisandy** [comment]
@cstony0917 Thanks for the report. Well, an identity file is used to codesign the application. If you have a valid certificate, type the name of the certificate in a file named `identity` and use it to sign the app. However the release task now skips the sign task if there is no `identity` file present in the root of the project and builds an installer. Fixed it in the latest commit. Do give it a try now.
