### ISSUE TITLE
Cannot find electron v0.27.2 from GitHub

### ISSUE THREAD

**Issue by afang** [whoisandie/yoda#8]
The `gulp-download-electron` module isn't working, so `gulp` cannot be run

```
/Users/fang/yoda/node_modules/gulp-download-electron/index.js:252
      throw new PluginError(PLUGIN_NAME, error.message);
            ^
Error: Cannot find electron v0.27.2 from GitHub
    at /Users/fang/yoda/node_modules/gulp-download-electron/index.js:252:13
    at /Users/fang/yoda/node_modules/gulp-download-electron/node_modules/async/lib/async.js:251:17
    at /Users/fang/yoda/node_modules/gulp-download-electron/node_modules/async/lib/async.js:148:21
    at /Users/fang/yoda/node_modules/gulp-download-electron/node_modules/async/lib/async.js:248:21
    at /Users/fang/yoda/node_modules/gulp-download-electron/node_modules/async/lib/async.js:612:34
    at /Users/fang/yoda/node_modules/gulp-download-electron/index.js:191:13
    at /Users/fang/yoda/node_modules/github-releases/lib/github.js:35:16
    at Request._callback (/Users/fang/yoda/node_modules/github-releases/lib/github.js:78:16)
    at Request.self.callback (/Users/fang/yoda/node_modules/github-releases/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
```

**Comment by whoisandie** [comment]
@afang Will try to hotfix it. Track v2 branch of yoda for further updates.
